version: '3.8'

services:
  db:
    container_name: db-radiant-sispa
    image: postgres:16.4-alpine
    ports:
      - '15001:5432'
    restart: 'no'
    labels:
      project: "sispa"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=radiant
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db:
    driver: local

networks:
  backend-network:
    name: sispa-radiant-backend-network
    driver: bridge
  frontend-network:
    name: sispa-radiant-frontend-network
    driver: bridge
