-- public.bank definition

-- Drop table

-- DROP TABLE public.bank;

CREATE TABLE public.bank (
                             admin_fee float8 NOT NULL,
                             interest_rate float8 NOT NULL,
                             created_at timestamptz(6) NOT NULL,
                             deleted_at timestamptz(6) NULL,
                             id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                             updated_at timestamptz(6) NULL,
                             created_by varchar(255) NOT NULL,
                             deleted_by varchar(255) NULL,
                             "name" varchar(255) NOT NULL,
                             updated_by varchar(255) NULL,
                             CONSTRAINT bank_name_key UNIQUE (name),
                             CONSTRAINT bank_pkey PRIMARY KEY (id)
);


-- public.client definition

-- Drop table

-- DROP TABLE public.client;

CREATE TABLE public.client (
                               created_at timestamp(6) NOT NULL,
                               deleted_at timestamp(6) NULL,
                               updated_at timestamp(6) NULL,
                               address varchar(255) NOT NULL,
                               contact varchar(255) NOT NULL,
                               created_by varchar(255) NOT NULL,
                               description varchar(255) NOT NULL,
                               email varchar(255) NOT NULL,
                               id varchar(255) NOT NULL,
                               industry varchar(255) NOT NULL,
                               "name" varchar(255) NOT NULL,
                               updated_by varchar(255) NOT NULL,
                               CONSTRAINT client_pkey PRIMARY KEY (id)
);


-- public.education_level definition

-- Drop table

-- DROP TABLE public.education_level;

CREATE TABLE public.education_level (
                                        deleted_at time(6) NULL,
                                        created_at timestamptz(6) NOT NULL,
                                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        updated_at timestamptz(6) NULL,
                                        created_by varchar(255) NOT NULL,
                                        deleted_by varchar(255) NULL,
                                        education varchar(255) NOT NULL,
                                        updated_by varchar(255) NULL,
                                        CONSTRAINT education_level_pkey PRIMARY KEY (id)
);


-- public.final_report definition

-- Drop table

-- DROP TABLE public.final_report;

CREATE TABLE public.final_report (
                                     created_at timestamptz(6) NOT NULL,
                                     deleted_at timestamp(6) NULL,
                                     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                     updated_at timestamptz(6) NULL,
                                     company varchar(255) NOT NULL,
                                     created_by varchar(255) NOT NULL,
                                     deleted_by varchar(255) NULL,
                                     "event" varchar(255) NOT NULL,
                                     event_date varchar(255) NOT NULL,
                                     file_name varchar(255) NOT NULL,
                                     updated_by varchar(255) NULL,
                                     CONSTRAINT final_report_pkey PRIMARY KEY (id)
);


-- public.item_category definition

-- Drop table

-- DROP TABLE public.item_category;

CREATE TABLE public.item_category (
                                      created_at timestamptz(6) NOT NULL,
                                      deleted_at timestamptz(6) NULL,
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      updated_at timestamptz(6) NULL,
                                      created_by varchar(255) NOT NULL,
                                      deleted_by varchar(255) NULL,
                                      "name" varchar(255) NOT NULL,
                                      updated_by varchar(255) NULL,
                                      CONSTRAINT item_category_pkey PRIMARY KEY (id)
);


-- public.item_status definition

-- Drop table

-- DROP TABLE public.item_status;

CREATE TABLE public.item_status (
                                    deleted_at time(6) NULL,
                                    created_at timestamptz(6) NOT NULL,
                                    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                    updated_at timestamptz(6) NULL,
                                    created_by varchar(255) NOT NULL,
                                    deleted_by varchar(255) NULL,
                                    status varchar(255) NOT NULL,
                                    updated_by varchar(255) NULL,
                                    CONSTRAINT item_status_pkey PRIMARY KEY (id)
);


-- public.purchase_order definition

-- Drop table

-- DROP TABLE public.purchase_order;

CREATE TABLE public.purchase_order (
                                       created_at timestamptz(6) NOT NULL,
                                       deleted_at timestamp(6) NULL,
                                       id int8 NOT NULL,
                                       updated_at timestamptz(6) NULL,
                                       company_address varchar(255) NOT NULL,
                                       company_name varchar(255) NOT NULL,
                                       created_by varchar(255) NOT NULL,
                                       date_created varchar(255) NOT NULL,
                                       date_signed varchar(255) NOT NULL,
                                       deleted_by varchar(255) NULL,
                                       file_name varchar(255) NOT NULL,
                                       no_po varchar(255) NOT NULL,
                                       place_signed varchar(255) NOT NULL,
                                       receiver varchar(255) NOT NULL,
                                       signee varchar(255) NOT NULL,
                                       terms varchar(255) NOT NULL,
                                       updated_by varchar(255) NULL,
                                       CONSTRAINT purchase_order_no_po_key UNIQUE (no_po),
                                       CONSTRAINT purchase_order_pkey PRIMARY KEY (id)
);


-- public."role" definition

-- Drop table

-- DROP TABLE public."role";

CREATE TABLE public."role" (
                               deleted_at time(6) NULL,
                               created_at timestamptz(6) NOT NULL,
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               updated_at timestamptz(6) NULL,
                               created_by varchar(255) NOT NULL,
                               deleted_by varchar(255) NULL,
                               "role" varchar(255) NOT NULL,
                               updated_by varchar(255) NULL,
                               CONSTRAINT role_pkey PRIMARY KEY (id)
);


-- public.transaction_category definition

-- Drop table

-- DROP TABLE public.transaction_category;

CREATE TABLE public.transaction_category (
                                             created_at timestamptz(6) NOT NULL,
                                             deleted_at timestamptz(6) NULL,
                                             id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                             updated_at timestamptz(6) NULL,
                                             created_by varchar(255) NOT NULL,
                                             deleted_by varchar(255) NULL,
                                             "name" varchar(255) NOT NULL,
                                             updated_by varchar(255) NULL,
                                             CONSTRAINT transaction_category_pkey PRIMARY KEY (id)
);


-- public.vendor definition

-- Drop table

-- DROP TABLE public.vendor;

CREATE TABLE public.vendor (
                               created_at timestamp(6) NOT NULL,
                               deleted_at timestamp(6) NULL,
                               updated_at timestamp(6) NULL,
                               address varchar(255) NOT NULL,
                               contact varchar(255) NOT NULL,
                               created_by varchar(255) NOT NULL,
                               description varchar(255) NOT NULL,
                               email varchar(255) NOT NULL,
                               id varchar(255) NOT NULL,
                               "name" varchar(255) NOT NULL,
                               service varchar(255) NOT NULL,
                               updated_by varchar(255) NOT NULL,
                               CONSTRAINT vendor_pkey PRIMARY KEY (id)
);


-- public.work_experience_category definition

-- Drop table

-- DROP TABLE public.work_experience_category;

CREATE TABLE public.work_experience_category (
                                                 deleted_at time(6) NULL,
                                                 created_at timestamptz(6) NOT NULL,
                                                 id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                 updated_at timestamptz(6) NULL,
                                                 category varchar(255) NOT NULL,
                                                 created_by varchar(255) NOT NULL,
                                                 deleted_by varchar(255) NULL,
                                                 updated_by varchar(255) NULL,
                                                 CONSTRAINT work_experience_category_pkey PRIMARY KEY (id)
);


-- public.account definition

-- Drop table

-- DROP TABLE public.account;

CREATE TABLE public.account (
                                created_at timestamptz(6) NOT NULL,
                                deleted_at timestamptz(6) NULL,
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                id_bank int8 NOT NULL,
                                updated_at timestamptz(6) NULL,
                                created_by varchar(255) NOT NULL,
                                deleted_by varchar(255) NULL,
                                "name" varchar(255) NOT NULL,
                                "no" varchar(255) NOT NULL,
                                updated_by varchar(255) NULL,
                                CONSTRAINT account_no_key UNIQUE (no),
                                CONSTRAINT account_pkey PRIMARY KEY (id),
                                CONSTRAINT fkpwnjbb07xe9slyywchx4ddqfm FOREIGN KEY (id_bank) REFERENCES public.bank(id) ON DELETE CASCADE
);


-- public.expense definition

-- Drop table

-- DROP TABLE public.expense;

CREATE TABLE public.expense (
                                amount float8 NOT NULL,
                                is_admin bool NULL,
                                transaction_date date NOT NULL,
                                created_at timestamptz(6) NOT NULL,
                                deleted_at timestamptz(6) NULL,
                                id_account int8 NOT NULL,
                                id_category int8 NOT NULL,
                                updated_at timestamptz(6) NULL,
                                created_by varchar(255) NOT NULL,
                                deleted_by varchar(255) NULL,
                                description varchar(255) NULL,
                                id varchar(255) NOT NULL,
                                updated_by varchar(255) NULL,
                                CONSTRAINT expense_pkey PRIMARY KEY (id),
                                CONSTRAINT fkf8etk6n4a9jgtrytqs92qapaw FOREIGN KEY (id_account) REFERENCES public.account(id) ON DELETE CASCADE,
                                CONSTRAINT fkiyo2nt9lssrxqprhgt4vphfsc FOREIGN KEY (id_category) REFERENCES public.transaction_category(id) ON DELETE CASCADE
);


-- public.image definition

-- Drop table

-- DROP TABLE public.image;

CREATE TABLE public.image (
                              created_at timestamptz(6) NOT NULL,
                              deleted_at timestamptz(6) NULL,
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              id_image int8 NULL,
                              updated_at timestamptz(6) NULL,
                              created_by varchar(255) NOT NULL,
                              deleted_by varchar(255) NULL,
                              file_name varchar(255) NOT NULL,
                              updated_by varchar(255) NULL,
                              file_data oid NOT NULL,
                              CONSTRAINT image_pkey PRIMARY KEY (id),
                              CONSTRAINT fkfmc18us4wy92ki8fob9jf0u92 FOREIGN KEY (id_image) REFERENCES public.final_report(id)
);


-- public.income definition

-- Drop table

-- DROP TABLE public.income;

CREATE TABLE public.income (
                               amount float8 NOT NULL,
                               is_interest bool NULL,
                               transaction_date date NOT NULL,
                               created_at timestamptz(6) NOT NULL,
                               deleted_at timestamptz(6) NULL,
                               id_account int8 NOT NULL,
                               id_category int8 NOT NULL,
                               updated_at timestamptz(6) NULL,
                               created_by varchar(255) NOT NULL,
                               deleted_by varchar(255) NULL,
                               description varchar(255) NULL,
                               id varchar(255) NOT NULL,
                               updated_by varchar(255) NULL,
                               CONSTRAINT income_pkey PRIMARY KEY (id),
                               CONSTRAINT fkj84dbrcjrxhdo5i46mx6nwx4g FOREIGN KEY (id_category) REFERENCES public.transaction_category(id) ON DELETE CASCADE,
                               CONSTRAINT fksvcip9bn013jvjjuxbv2l8p96 FOREIGN KEY (id_account) REFERENCES public.account(id) ON DELETE CASCADE
);


-- public.invoice definition

-- Drop table

-- DROP TABLE public.invoice;

CREATE TABLE public.invoice (
                                ppn_pecentage float8 NOT NULL,
                                created_at timestamptz(6) NOT NULL,
                                deleted_at timestamptz(6) NULL,
                                id int8 NOT NULL,
                                id_purchase_order int8 NULL,
                                ppn int8 NOT NULL,
                                sub_total int8 NOT NULL,
                                total int8 NOT NULL,
                                updated_at timestamptz(6) NULL,
                                account_number varchar(255) NOT NULL,
                                bank_name varchar(255) NOT NULL,
                                created_by varchar(255) NOT NULL,
                                date_created varchar(255) NOT NULL,
                                date_paid varchar(255) NOT NULL,
                                date_signed varchar(255) NOT NULL,
                                deleted_by varchar(255) NULL,
                                "event" varchar(255) NOT NULL,
                                file_name varchar(255) NOT NULL,
                                no_invoice varchar(255) NOT NULL,
                                no_po varchar(255) NOT NULL,
                                on_behalf varchar(255) NOT NULL,
                                place_signed varchar(255) NOT NULL,
                                receiver varchar(255) NOT NULL,
                                signee varchar(255) NOT NULL,
                                spelled_out varchar(255) NOT NULL,
                                updated_by varchar(255) NULL,
                                CONSTRAINT invoice_no_invoice_key UNIQUE (no_invoice),
                                CONSTRAINT invoice_pkey PRIMARY KEY (id),
                                CONSTRAINT fk6kflikn8kfhho2xr7j7h8pkik FOREIGN KEY (id_purchase_order) REFERENCES public.purchase_order(id)
);


-- public.item definition

-- Drop table

-- DROP TABLE public.item;

CREATE TABLE public.item (
                             created_at timestamptz(6) NOT NULL,
                             deleted_at timestamptz(6) NULL,
                             id int8 NOT NULL,
                             id_category int8 NOT NULL,
                             id_item_status int8 NOT NULL,
                             price_per_unit int8 NOT NULL,
                             updated_at timestamptz(6) NULL,
                             created_by varchar(255) NOT NULL,
                             deleted_by varchar(255) NULL,
                             description varchar(255) NULL,
                             title varchar(255) NOT NULL,
                             unit varchar(255) NOT NULL,
                             updated_by varchar(255) NULL,
                             CONSTRAINT item_pkey PRIMARY KEY (id),
                             CONSTRAINT fkaw3ja9hcjls9rol0nvrevk6b FOREIGN KEY (id_item_status) REFERENCES public.item_status(id) ON DELETE CASCADE,
                             CONSTRAINT fkc27xb1quvcwiwg90fd9j5u00v FOREIGN KEY (id_category) REFERENCES public.item_category(id) ON DELETE CASCADE
);


-- public.purchase_order_client definition

-- Drop table

-- DROP TABLE public.purchase_order_client;

CREATE TABLE public.purchase_order_client (
                                              id_purchase_order int8 NOT NULL,
                                              id_client varchar(255) NOT NULL,
                                              CONSTRAINT fk5gxm4pkrqn567jlceabwodc8a FOREIGN KEY (id_client) REFERENCES public.client(id),
                                              CONSTRAINT fk5x589syd6mwe4830aq4adtbfi FOREIGN KEY (id_purchase_order) REFERENCES public.purchase_order(id)
);


-- public.purchase_order_item definition

-- Drop table

-- DROP TABLE public.purchase_order_item;

CREATE TABLE public.purchase_order_item (
                                            id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                            item_id int8 NOT NULL,
                                            purchase_order_id int8 NOT NULL,
                                            volume int8 NOT NULL,
                                            CONSTRAINT purchase_order_item_pkey PRIMARY KEY (id),
                                            CONSTRAINT fk6hnf77cwyb21thxqtphoatybv FOREIGN KEY (item_id) REFERENCES public.item(id),
                                            CONSTRAINT fkmj122necubadvuquvjoq967y7 FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_order(id)
);


-- public.purchase_order_vendor definition

-- Drop table

-- DROP TABLE public.purchase_order_vendor;

CREATE TABLE public.purchase_order_vendor (
                                              id_purchase_order int8 NOT NULL,
                                              id_vendor varchar(255) NOT NULL,
                                              CONSTRAINT fkhmw4m8lr1t95kdtpesg7srjnj FOREIGN KEY (id_purchase_order) REFERENCES public.purchase_order(id),
                                              CONSTRAINT fkmthynbgrenxgymylyjbf2w13w FOREIGN KEY (id_vendor) REFERENCES public.vendor(id)
);


-- public.user_model definition

-- Drop table

-- DROP TABLE public.user_model;

CREATE TABLE public.user_model (
                                   date_of_birth date NULL,
                                   created_at timestamptz(6) NOT NULL,
                                   deleted_at timestamptz(6) NULL,
                                   id int8 NOT NULL,
                                   id_role int8 NOT NULL,
                                   updated_at timestamptz(6) NULL,
                                   address varchar(255) NULL,
                                   created_by varchar(255) NOT NULL,
                                   deleted_by varchar(255) NULL,
                                   email varchar(255) NOT NULL,
                                   "name" varchar(255) NOT NULL,
                                   "password" varchar(255) NOT NULL,
                                   phone_number varchar(255) NULL,
                                   place_of_birth varchar(255) NULL,
                                   updated_by varchar(255) NULL,
                                   username varchar(255) NOT NULL,
                                   CONSTRAINT user_model_email_key UNIQUE (email),
                                   CONSTRAINT user_model_pkey PRIMARY KEY (id),
                                   CONSTRAINT user_model_username_key UNIQUE (username),
                                   CONSTRAINT fkgrgd53qi4atdj5692ichk9mo8 FOREIGN KEY (id_role) REFERENCES public."role"(id) ON DELETE CASCADE
);


-- public.freelancer definition

-- Drop table

-- DROP TABLE public.freelancer;

CREATE TABLE public.freelancer (
                                   is_working bool NULL,
                                   approved_at timestamptz(6) NULL,
                                   id int8 NOT NULL,
                                   id_education_level int8 NOT NULL,
                                   rejected_at timestamptz(6) NULL,
                                   display_nik varchar(255) NULL,
                                   nik varchar(255) NULL,
                                   reason varchar(255) NULL,
                                   CONSTRAINT freelancer_nik_key UNIQUE (nik),
                                   CONSTRAINT freelancer_pkey PRIMARY KEY (id),
                                   CONSTRAINT fk1h5skwql67u6p4jidf19pfcws FOREIGN KEY (id_education_level) REFERENCES public.education_level(id) ON DELETE CASCADE,
                                   CONSTRAINT fk1uqtmsdpajew1d6w1jvub3qe4 FOREIGN KEY (id) REFERENCES public.user_model(id)
);


-- public.work_experience definition

-- Drop table

-- DROP TABLE public.work_experience;

CREATE TABLE public.work_experience (
                                        deleted_at time(6) NULL,
                                        end_date date NULL,
                                        is_still_working bool NOT NULL,
                                        start_date date NOT NULL,
                                        created_at timestamptz(6) NOT NULL,
                                        id int8 NOT NULL,
                                        id_freelancer int8 NOT NULL,
                                        id_work_experience_category int8 NOT NULL,
                                        updated_at timestamptz(6) NULL,
                                        created_by varchar(255) NOT NULL,
                                        deleted_by varchar(255) NULL,
                                        description varchar(255) NOT NULL,
                                        title varchar(255) NOT NULL,
                                        updated_by varchar(255) NULL,
                                        CONSTRAINT work_experience_pkey PRIMARY KEY (id),
                                        CONSTRAINT fkd4s9mqk525mv96p8m1l672lal FOREIGN KEY (id_freelancer) REFERENCES public.freelancer(id) ON DELETE CASCADE,
                                        CONSTRAINT fktggdg579q93n2v2je5o7bepx9 FOREIGN KEY (id_work_experience_category) REFERENCES public.work_experience_category(id) ON DELETE CASCADE
);


-- INSERT role
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public."role" WHERE role = 'ADMIN') THEN
        INSERT INTO public."role" (created_at, created_by, role)
        VALUES (NOW(), 'system', 'ADMIN');
END IF;

    IF NOT EXISTS (SELECT 1 FROM public."role" WHERE role = 'MANAJEMEN') THEN
        INSERT INTO public."role" (created_at, created_by, role)
        VALUES (NOW(), 'system', 'MANAJEMEN');
END IF;

    IF NOT EXISTS (SELECT 1 FROM public."role" WHERE role = 'FINANCE') THEN
        INSERT INTO public."role" (created_at, created_by, role)
        VALUES (NOW(), 'system', 'FINANCE');
END IF;

    IF NOT EXISTS (SELECT 1 FROM public."role" WHERE role = 'MARKETING') THEN
        INSERT INTO public."role" (created_at, created_by, role)
        VALUES (NOW(), 'system', 'MARKETING');
END IF;

    IF NOT EXISTS (SELECT 1 FROM public."role" WHERE role = 'PURCHASING') THEN
        INSERT INTO public."role" (created_at, created_by, role)
        VALUES (NOW(), 'system', 'PURCHASING');
END IF;

    IF NOT EXISTS (SELECT 1 FROM public."role" WHERE role = 'FREELANCER') THEN
        INSERT INTO public."role" (created_at, created_by, role)
        VALUES (NOW(), 'system', 'FREELANCER');
END IF;
END $$;


-- INSERT user_model
DO $$
DECLARE
role_id BIGINT;
    next_id BIGINT;
BEGIN
    -- ADMIN
SELECT id INTO role_id FROM public."role" WHERE role = 'ADMIN';
IF NOT EXISTS (
        SELECT 1 FROM public.user_model WHERE email = 'admin@gmail.com' OR username = 'admin'
    ) THEN
SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM public.user_model;
INSERT INTO public.user_model (
    id, created_at, created_by, id_role, email, username, "name", "password"
) VALUES (
             next_id, NOW(), 'system', role_id,
             'admin@gmail.com', 'admin', 'Admin', 'admin'
         );
END IF;

    -- MANAJEMEN
SELECT id INTO role_id FROM public."role" WHERE role = 'MANAJEMEN';
IF NOT EXISTS (
        SELECT 1 FROM public.user_model WHERE email = 'manajemen@gmail.com' OR username = 'manajemen'
    ) THEN
SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM public.user_model;
INSERT INTO public.user_model (
    id, created_at, created_by, id_role, email, username, "name", "password"
) VALUES (
             next_id, NOW(), 'system', role_id,
             'manajemen@gmail.com', 'manajemen', 'Manajemen', 'manajemen'
         );
END IF;

    -- FINANCE
SELECT id INTO role_id FROM public."role" WHERE role = 'FINANCE';
IF NOT EXISTS (
        SELECT 1 FROM public.user_model WHERE email = 'finance@gmail.com' OR username = 'finance'
    ) THEN
SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM public.user_model;
INSERT INTO public.user_model (
    id, created_at, created_by, id_role, email, username, "name", "password"
) VALUES (
             next_id, NOW(), 'system', role_id,
             'finance@gmail.com', 'finance', 'Finance', 'finance'
         );
END IF;

    -- MARKETING
SELECT id INTO role_id FROM public."role" WHERE role = 'MARKETING';
IF NOT EXISTS (
        SELECT 1 FROM public.user_model WHERE email = 'marketing@gmail.com' OR username = 'marketing'
    ) THEN
SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM public.user_model;
INSERT INTO public.user_model (
    id, created_at, created_by, id_role, email, username, "name", "password"
) VALUES (
             next_id, NOW(), 'system', role_id,
             'marketing@gmail.com', 'marketing', 'Marketing', 'marketing'
         );
END IF;

    -- PURCHASING
SELECT id INTO role_id FROM public."role" WHERE role = 'PURCHASING';
IF NOT EXISTS (
        SELECT 1 FROM public.user_model WHERE email = 'purchasing@gmail.com' OR username = 'purchasing'
    ) THEN
SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM public.user_model;
INSERT INTO public.user_model (
    id, created_at, created_by, id_role, email, username, "name", "password"
) VALUES (
             next_id, NOW(), 'system', role_id,
             'purchasing@gmail.com', 'purchasing', 'Purchasing', 'purchasing'
         );
END IF;
END $$;


-- INSERT work_experience_category
DO $$
DECLARE
category_name TEXT;
BEGIN
    FOREACH category_name IN ARRAY
        '{ASISTEN MATA KULIAH,BOOTCAMP,FREELANCE,FULLTIME,KEGIATAN KAMPUS,KONTRAK,LOMBA,MAGANG,ORGANISASI,PARUH WAKTU,PENGABDIAN MASYARAKAT,PENGALAMAN MENGAJAR,PROYEK SUKARELA,RISET,TRAINING,WIRAUSAHA,LAINNYA}'::text[]
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM public.work_experience_category WHERE category = category_name
        ) THEN
            INSERT INTO public.work_experience_category (
                created_at, created_by, category
            ) VALUES (
                NOW(), 'system', category_name
            );
END IF;
END LOOP;
END $$;




-- INSERT item_category
DO $$
DECLARE
category_name TEXT;
BEGIN
    FOREACH category_name IN ARRAY '{ELEKTRONIK,FURNITUR,PAKAIAN,MAKANAN,MINUMAN,ALAT TULIS,MAINAN,PERLENGKAPAN DAPUR,PERLENGKAPAN MANDI,OBAT-OBATAN,PERALATAN OLAHRAGA,BUKU,ALAT KEBERSIHAN,PERLENGKAPAN BAYI,PERLENGKAPAN HEWAN,ALAT MUSIK,AKSESORIS,KOSMETIK,PERKAKAS,PERLENGKAPAN KANTOR}'::text[]
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM public.item_category WHERE name = category_name
        ) THEN
            INSERT INTO public.item_category (
                created_at, created_by, name
            ) VALUES (
                NOW(), 'system', category_name
            );
END IF;
END LOOP;
END $$;


-- INSERT item_status
DO $$
DECLARE
status_name TEXT;
BEGIN
    FOREACH status_name IN ARRAY '{TERSEDIA,TIDAK TERSEDIA,DIPERBAIKI}'::text[]
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM public.item_status WHERE status = status_name
        ) THEN
            INSERT INTO public.item_status (
                created_at, created_by, status
            ) VALUES (
                NOW(), 'system', status_name
            );
END IF;
END LOOP;
END $$;


-- INSERT education_level
DO $$
DECLARE
edu_level TEXT;
BEGIN
    FOREACH edu_level IN ARRAY '{TK,SD,SMP,SMA,SMK,D1,D2,D3,D4,S1,S2,S3,LAINNYA}'::text[]
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM public.education_level WHERE education = edu_level
        ) THEN
            INSERT INTO public.education_level (
                created_at, created_by, education
            ) VALUES (
                NOW(), 'system', edu_level
            );
END IF;
END LOOP;
END $$;


-- INSERT transaction_category
DO $$
DECLARE
txn_cat TEXT;
BEGIN
    FOREACH txn_cat IN ARRAY '{PENDAPATAN KLIEN,BIAYA VENUE,DEKORASI DAN SETTING,TALENT DAN MC,PERIZINAN DAN LEGALITAS,KONSUMSI DAN KATERING,TRANSPORTASI DAN AKOMODASI,PROMOSI DAN MARKETING,CETAK DAN MERCHANDISE,GAJI DAN OPERASIONAL KARYAWAN,BUNGA BANK,ADMINISTRASI BANK,LAIN-LAIN}'::text[]
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM public.transaction_category WHERE "name" = txn_cat
        ) THEN
            INSERT INTO public.transaction_category (
                created_at, created_by, "name"
            ) VALUES (
                NOW(), 'system', txn_cat
            );
END IF;
END LOOP;
END $$;