spring:
  main:
    allow-circular-references: true
  profiles:
    active: 'dev'
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true
manpromanpro:
  app:
    jwtSecret: "${JWT_SECRET_KEY}"
    jwtExpirationMs: 86400000
