spring:
  main:
    allow-circular-references: true
  profiles:
    active: 'dev'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
manpromanpro:
  app:
    jwtSecret: "${JWT_SECRET_KEY}"
    jwtExpirationMs: 86400000
