name: Sync from GitLab

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch: # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add GitLab remote
        run: |
          git remote add upstream https://gitlab.cs.ui.ac.id/propensi-2024-2025-genap/kelas-b/b01-radiant-be.git
          git fetch upstream

      - name: Reset main branch to GitLab
        run: |
          git checkout main
          git reset --hard upstream/main

      - name: Push to GitHub
        run: |
          git push origin main --force
          git push origin --tags --force
