name: Hostinger CI/CD Pipeline

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch: # Manual trigger


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Compile project to .jar
        run: |
          ./gradlew clean assemble

      - name: List contents of build/libs
        run: |
          ls -la build/libs

      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: build/libs/backend-0.0.1-SNAPSHOT.jar

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} -f Dockerfile .

      - name: Push image to registry
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.DEPLOY_SERVER }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts  # Set permissions for known_hosts

      - name: Deploy to Hostinger VPS
        run: |
          ssh "${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_SERVER }}" "mkdir -p ~/backend/"
          rsync -rahv docker-compose.yml "${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_SERVER }}:~/backend/"
          rsync -rahv docker-compose-deploy.yml "${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_SERVER }}:~/backend/"
          ssh "${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_SERVER }}" "
            export IMAGE_NAME=${{ secrets.IMAGE_NAME }} &&
            export DATABASE_URL_DEV=${{ secrets.DATABASE_URL_DEV }} &&
            export DATABASE_USERNAME_DEV=${{ secrets.DATABASE_USERNAME_DEV }} &&
            export DATABASE_PASSWORD_DEV=${{ secrets.DATABASE_PASSWORD_DEV }} &&
            export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} &&
            docker rm -f backend-sispa || true &&
            cd ~/backend &&
            echo 'Current directory:' && pwd &&
            docker compose -f docker-compose-deploy.yml up -d --pull always
          "

  clean:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.DEPLOY_SERVER }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts  # Set permissions for known_hosts

      - name: Clean up old Docker images
        run: |
          ssh "${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_SERVER }}" "docker system prune -f"